### ISSUE TITLE
Anatomy of a DDoS Attack: From Host Infection to Service Denial

### ISSUE THREAD

**Issue by ozeliurs** [ozeliurs/SDN-Security#7]
# Chapters

- [x] The Sandbox
- [x] Building a simple virus
- [x] Host Compromise
- [x] Launching the Attack
- [x] Demo
- [x] Forensics

# Improvements Proposals

- [x] Add a video for the demo of remove the demo

# TODO

- [x] Test exploit
- [x] Test C2 Server
- [x] Test Mininet Script
- [x] Check if `tcpdump` works
- [x] Check if bwm-ng works
- [x] Test PHP Exploit
- [x] Test SSH Bruteforce

**Comment by ozeliurs** [comment]
TCPDump OK
<img width="1680" alt="Capture d’écran 2024-06-18 à 15 12 17" src="https://github.com/ozeliurs/SDN-Security/assets/59318604/7c05ce70-631c-4068-a97c-0e516c82a994">
[captures.zip](https://github.com/user-attachments/files/15882648/captures.zip)

**Comment by ozeliurs** [comment]
bwm-ng OK

<img width="975" alt="Capture d’écran 2024-06-18 à 15 13 34" src="https://github.com/ozeliurs/SDN-Security/assets/59318604/3c8308a3-5a9c-4419-a92e-0c4c0dcf2a17">

[mon.csv](https://github.com/user-attachments/files/15882650/mon.csv)
